import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';

const scene=new THREE.Scene(); scene.background=new THREE.Color(0x9ed7ff); scene.fog=new THREE.Fog(0x9ed7ff,70,190);
const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,300); camera.position.set(38,34,48);
const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,1.7)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; document.body.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement); controls.target.set(0,0,0); controls.maxPolarAngle=Math.PI/2.05; controls.minDistance=8; controls.maxDistance=120; controls.enableDamping=true; controls.dampingFactor=.08; controls.rotateSpeed=.42; controls.zoomSpeed=.55; controls.panSpeed=.35;
scene.add(new THREE.HemisphereLight(0xbfe7ff,0x6b5133,2.1)); const sun=new THREE.DirectionalLight(0xfff1c7,3.2); sun.position.set(-35,65,35); sun.castShadow=true; sun.shadow.mapSize.set(2048,2048); scene.add(sun);
const ray=new THREE.Raycaster(), mouse=new THREE.Vector2(); const objects=new THREE.Group(); scene.add(objects); const map=[]; let selected='wheat';
const mat=(c,rough=1)=>new THREE.MeshStandardMaterial({color:c,roughness:rough});
const M={grass:mat(0x5d9a43),grass2:mat(0x7eaf55),dirt:mat(0x9b6a3d),wood:mat(0x70452c),wood2:mat(0x9a6844),stone:mat(0x77736b),dark:mat(0x17130f),water:mat(0x2e9fd0,.25),roof:mat(0x60402f),wheat:mat(0xd4ae4b),leaf:mat(0x2f7d39),leaf2:mat(0x4d963f),apple:mat(0xd62c2c),metal:mat(0x7d7a72)};
function box(w,h,d,m,x=0,y=h/2,z=0){let o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;return o}
function cyl(r,h,m,x=0,y=h/2,z=0,seg=12){let o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,seg),m);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;return o}
function roof(w,d,h,m){let g=new THREE.Group();let r=new THREE.Mesh(new THREE.ConeGeometry(Math.max(w,d)*.72,h,4),m);r.rotation.y=Math.PI/4;r.position.y=h/2;g.add(r);return g}
function ground(){const g=new THREE.PlaneGeometry(140,105,45,34);const p=g.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getY(i);let y=.4*Math.sin(x*.12)*Math.cos(z*.13)+.18*Math.sin(z*.31);p.setZ(i,y)}g.rotateX(-Math.PI/2);const mesh=new THREE.Mesh(g,M.grass);mesh.receiveShadow=true;objects.add(mesh);return mesh}
function path(x,z,w,d,rot=0){let o=box(w,.08,d,M.dirt,x,.04,z);o.rotation.y=rot;objects.add(o);return o}
function water(){let g=new THREE.PlaneGeometry(140,20,60,8);let m=M.water.clone();m.transparent=true;m.opacity=.9;let o=new THREE.Mesh(g,m);o.rotation.x=-Math.PI/2;o.position.set(0,.05,42);objects.add(o);for(let i=0;i<14;i++){let r=.15+Math.random()*.45;let s=cyl(r,r*.55,M.stone,Math.random()*65-32,.3,34+Math.random()*14,10);objects.add(s)}}
function wheat(x,z){let g=new THREE.Group();for(let i=0;i<22;i++){let h=1.3+Math.random()*1.2;let stem=cyl(.025,h,M.wheat,Math.random()*1.1-.55,h/2,Math.random()*1.1-.55,5);stem.rotation.z=(Math.random()-.5)*.18;g.add(stem);let head=cyl(.09,.5,M.wheat,stem.position.x,h+.12,stem.position.z,6);head.scale.z=.7;g.add(head)}g.position.set(x,.1,z);objects.add(g);return g}
function tree(x,z,apple=false){let g=new THREE.Group();g.add(cyl(.28,2.4,M.wood,0,1.2,0,9));for(let i=0;i<6;i++){let a=i*Math.PI/3,s=.9+Math.random()*.7,c=new THREE.Mesh(new THREE.IcosahedronGeometry(s,1),i%2?M.leaf:M.leaf2);c.position.set(Math.cos(a)*.65,2.8+Math.random()*1.2,Math.sin(a)*.65);c.castShadow=true;g.add(c);if(apple&&i%2===0){let ap=new THREE.Mesh(new THREE.SphereGeometry(.13,10,8),M.apple);ap.position.copy(c.position).add(new THREE.Vector3(Math.cos(a)*.5,-.25,Math.sin(a)*.5));g.add(ap)}}g.position.set(x,.1,z);objects.add(g);return g}
function building(x,z,w,d,h,type){let g=new THREE.Group();g.add(box(w,h,d,M.wood2));g.add(roof(w,d,h*.75,M.roof));g.add(box(.75,1.35,.08,M.dark,0,.68,d/2+.05));g.position.set(x,0,z);objects.add(g);return g}
function sawmill(x,z){let g=new THREE.Group();g.add(box(6,1.8,4,M.wood2));g.add(roof(6,4,3,M.roof));for(let i=0;i<5;i++){let log=cyl(.38,2.5,M.wood,-2.7+i*.55,.45,2.3,10);log.rotation.z=Math.PI/2;g.add(log)}let blade=new THREE.Mesh(new THREE.CylinderGeometry(1,1,.15,24),M.metal);blade.rotation.x=Math.PI/2;blade.position.set(-1.6,1.5,2.25);g.add(blade);g.position.set(x,0,z);objects.add(g)}
function mill(x,z){let g=new THREE.Group();g.add(cyl(2.2,5,M.stone));g.add(roof(4.6,4.6,2.4,M.roof));for(let i=0;i<4;i++){let arm=box(.22,4,.18,M.wood,0,3.1,2.2);arm.rotation.y=i*Math.PI/2;arm.rotation.x=.55;g.add(arm)}g.position.set(x,0,z);objects.add(g)}
function well(x,z){let g=new THREE.Group();for(let i=0;i<16;i++){let a=i*Math.PI*2/16,r=1.4;g.add(cyl(.28,.55,M.stone,Math.cos(a)*r,.3,Math.sin(a)*r,8))}let waterM=M.water.clone();g.add(cyl(1.1,.08,waterM,0,.57,0,20));g.position.set(x,0,z);objects.add(g)}
function cave(x,z){let g=new THREE.Group();g.add(box(8,5,3,M.stone,0,2.5,0));g.add(box(4.8,3.4,3.2,M.dark,0,1.8,.2));for(let i=0;i<9;i++){let a=-Math.PI/2+i*Math.PI/8;g.add(cyl(.35+Math.random()*.35,1.2+Math.random(),M.stone,Math.cos(a)*3.4,3.2+Math.sin(a)*1.5,.2,8))}g.position.set(x,0,z);objects.add(g)}
function rock(x,z){let s=.5+Math.random()*1.3,o=new THREE.Mesh(new THREE.DodecahedronGeometry(s,0),M.stone);o.position.set(x,s*.55,z);o.rotation.set(Math.random(),Math.random(),Math.random());o.castShadow=o.receiveShadow=true;objects.add(o)}
function clearScene(){while(objects.children.length)objects.remove(objects.children[0])}
function buildBase(){clearScene();ground();water();path(0,10,5,68);for(let x=-27;x<=-8;x+=3.2)for(let z=-34;z<=-8;z+=2.5)wheat(x+Math.random()*.7,z+Math.random()*.7);cave(26,-34);tree(16,-24,true);sawmill(-19,-2);mill(17,-4);building(-14,9,12,8,5,'house');building(17,10,7,6,3.8,'shop');building(-21,21,7,6,3.6,'small');well(-4,20);for(let i=0;i<28;i++)rock((Math.random()-.5)*62,-32+Math.random()*72);for(let i=0;i<22;i++)tree((Math.random()-.5)*62,-35+Math.random()*70)}
function add(type,x,z){if(type==='wheat')for(let i=0;i<4;i++)wheat(x+(Math.random()-.5)*2,z+(Math.random()-.5)*2);else if(type==='tree')tree(x,z);else if(type==='apple')tree(x,z,true);else if(type==='rock')rock(x,z);else if(type==='house')building(x,z,8,6,4.5,'house');else if(type==='smallHouse')building(x,z,5,4,3.2,'small');else if(type==='sawmill')sawmill(x,z);else if(type==='mill')mill(x,z);else if(type==='well')well(x,z);else if(type==='shop')building(x,z,6,4,3.8,'shop');else if(type==='cave')cave(x,z);else if(type==='path')path(x,z,5,12,0);map.push({type,x,z});toast(type+' colocado')}
function toast(t){let e=document.getElementById('toast');e.textContent=t;e.style.opacity=1;clearTimeout(window.tt);window.tt=setTimeout(()=>e.style.opacity=0,900)}
let pressX=0,pressY=0,pressTime=0;renderer.domElement.addEventListener('pointerdown',e=>{if(e.button!==0)return;pressX=e.clientX;pressY=e.clientY;pressTime=performance.now()});renderer.domElement.addEventListener('pointerup',e=>{if(e.button!==0)return;if(Math.hypot(e.clientX-pressX,e.clientY-pressY)>9||performance.now()-pressTime>450)return;mouse.x=e.clientX/innerWidth*2-1;mouse.y=-(e.clientY/innerHeight)*2+1;ray.setFromCamera(mouse,camera);let hit=ray.intersectObjects(objects.children,true)[0];if(!hit)return;let p=hit.point;if(selected==='erase'){let target=hit.object;while(target.parent&&target.parent!==objects)target=target.parent;target.removeFromParent();toast('Objeto borrado');return}add(selected,Math.round(p.x),Math.round(p.z))});
document.querySelectorAll('#palette button').forEach(b=>b.onclick=()=>{selected=b.dataset.type;document.querySelectorAll('#palette button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});document.querySelector('#palette button').classList.add('active');
document.getElementById('refBtn').onclick=()=>document.getElementById('reference').classList.add('show');document.getElementById('closeRef').onclick=()=>document.getElementById('reference').classList.remove('show');
document.getElementById('saveBtn').onclick=()=>{localStorage.eggaroMap=JSON.stringify(map);toast('Mapa guardado')};document.getElementById('exportBtn').onclick=()=>{let b=new Blob([JSON.stringify({version:1,objects:map},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='eggaro-map.json';a.click();toast('JSON exportado')};
buildBase();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});(function loop(){requestAnimationFrame(loop);controls.update();renderer.render(scene,camera)})();
